greeting:
  name: Dakota
  coffee: ${greeting.name} is drinking Cafe Cereza
spring:
  application:
    name: coffeemachine
  datasource:
    url: jdbc:mysql://localhost:3306/coffeesmachine?createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org:
      formation:
        controller:
          CoffeeController: TRACE

build:  
  version: "1.0"

account:
  message: "Welcome to Coffee PRD"
  details:
    name: "Bob"
    email: "florian@test.fr"
  phone:
    - 1234569874
    - 789654135
